import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/global/footer";
import { Navbar } from "@/components/global/navbar";



export const metadata: Metadata = {
  title: "Novasce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={` antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
